/* AR PERIO — cases-data.js (portado de src/data/clinicalCases.ts) */
/**
 * AR PERIO — Casos clínicos integrados.
 * ESTRUCTURA EDITABLE: el panel docente crea nuevos casos con la misma
 * forma (ClinicalCase) sin tocar código; se almacenan en el navegador y
 * pueden exportarse/importarse como JSON.
 */
const BUILTIN_CASES = [
    {
        id: "caso-gingivitis",
        title: "Caso 1 · Sangrado al cepillado en paciente joven",
        difficulty: "basico",
        builtin: true,
        patient: {
            age: 23,
            sex: "F",
            chiefComplaint: "«Mis encías sangran cuando me cepillo y se ven rojas desde hace dos meses».",
            history: [
                "Sangrado al cepillado indoloro de 2 meses de evolución, progresivo.",
                "Sin antecedentes médicos de interés. No toma medicación.",
                "Cepillado una vez al día, técnica horizontal vigorosa, sin hilo dental.",
                "Última visita al dentista hace 3 años (limpieza).",
            ],
            background: ["Estudiante universitaria", "Sin alergias", "Menstruación regular"],
            habits: ["No fuma", "Dieta con alta frecuencia de hidratos de carbono", "Baja motivación de higiene interproximal"],
        },
        clinicalFindings: [
            "Eritema marginal difuso en ambos maxilares con pérdida de la estipulación.",
            "Márgenes redondeados y edematosos; papillas aumentadas de volumen.",
            "Placa abundante en tercios cervicales y ausencia de cálculo significativo.",
            "BOP del 80 % de los sitios sondados.",
            "Sondaje de 3–4 mm generalizado con NIC conservado (margen coronal por edema).",
            "Sin movilidad ni recesiones. Radiográficamente sin pérdida ósea.",
        ],
        photos: [{ caption: "Vestibular maxilar: eritema y edema marginal (ilustración esquemática)", kind: "gingivitis" }],
        perio: {
            toothId: "incisivo-central-sup",
            sites: {
                VMes: { pd: 3.5, rec: 0, bop: true, sup: false },
                VMed: { pd: 3.2, rec: 0, bop: true, sup: false },
                VDis: { pd: 3.4, rec: 0, bop: true, sup: false },
                PMes: { pd: 3.6, rec: 0, bop: true, sup: false },
                PMed: { pd: 3.3, rec: 0, bop: false, sup: false },
                PDis: { pd: 3.5, rec: 0, bop: true, sup: false },
            },
            mobility: 0,
        },
        conditionId: "gingivitis",
        questions: [
            {
                id: "cg1-diag",
                kind: "diagnostico",
                prompt: "Con los hallazgos presentados, ¿cuál es el diagnóstico periodontal más probable?",
                options: [
                    "Periodontitis estadio I grado B",
                    "Gingivitis inducida por biofilm dental",
                    "Periodontitis estadio III grado C",
                    "Encía sana con sangrado fisiológico",
                ],
                correct: [1],
                multi: false,
                explanation: "Hay inflamación con BOP del 80 % y seudobolsas de 3–4 mm con NIC conservado, sin pérdida ósea ni movilidad: gingivitis inducida por biofilm. No cumple criterios de periodontitis porque no hay pérdida de inserción (NIC desde CEJ normal).",
            },
            {
                id: "cg1-hallazgos",
                kind: "hallazgos",
                prompt: "Selecciona TODOS los hallazgos que apoyan el diagnóstico de gingivitis (y no de periodontitis).",
                options: [
                    "NIC conservado en todos los sitios",
                    "BOP del 80 %",
                    "Sondaje de 3–4 mm con margen coronal edematoso",
                    "Ausencia de pérdida ósea radiográfica",
                    "Movilidad grado 1",
                    "Recesión de 2 mm",
                ],
                correct: [0, 1, 2, 3],
                multi: true,
                explanation: "El NIC conservado, el BOP, las seudobolsas con margen coronal y la ausencia de pérdida ósea definen gingivitis. La movilidad y las recesiones son signos de destrucción y aquí están ausentes.",
            },
            {
                id: "cg1-riesgo",
                kind: "riesgo",
                prompt: "¿Qué factores de riesgo identificas en este caso?",
                options: [
                    "Higiene oral deficiente",
                    "Tabaquismo",
                    "Diabetes mellitus no controlada",
                    "Acumulación de biofilm por técnica de cepillado inadecuada",
                ],
                correct: [0, 3],
                multi: true,
                explanation: "La higiene deficiente (una vez al día, sin hilo, técnica incorrecta) es el factor determinante. No fuma ni tiene diabetes.",
            },
            {
                id: "cg1-pronostico",
                kind: "pronostico",
                prompt: "¿Cuál es el pronóstico periodontal con el tratamiento adecuado?",
                options: [
                    "Reservado: espera pérdida dentaria",
                    "Excelente: la lesión es reversible con control de biopelícula",
                    "Malo: requiere cirugía regenerativa",
                    "Solo puede estabilizarse, no revertirse",
                ],
                correct: [1],
                multi: false,
                explanation: "La gingivitis es completamente reversible al eliminar el biofilm y corregir la higiene: la encía recupera salud en 1–2 semanas.",
            },
            {
                id: "cg1-plan",
                kind: "plan",
                prompt: "¿Cuál es la primera línea de tratamiento indicada?",
                options: [
                    "Cirugía de colgajo con regeneración guiada",
                    "Instrucción de higiene + profilaxis mecánica profesional y reevaluación",
                    "Extracción del 11 por pronóstico pobre",
                    "Antibióticos sistémicos sin desbridamiento",
                ],
                correct: [1],
                multi: false,
                explanation: "La terapia etiológica (motivación, instrucción de higiene y profilaxis supragingival) resuelve la gingivitis; la reevaluación confirma la resolución. Nada justifica cirugía, extracciones ni antibióticos.",
            },
        ],
        teachingPoints: [
            "La PD aumentada con margen coronal y NIC normal es una seudobolsa, no una bolsa verdadera.",
            "El BOP es el signo más sensible de inflamación: aquí es el eje del diagnóstico.",
            "La gingivitis es reversible; la periodontitis, no (solo estabilizable/regenerable en parte).",
        ],
    },
    {
        id: "caso-periodontitis",
        title: "Caso 2 · Movilidad y espacios en paciente fumadora",
        difficulty: "intermedio",
        builtin: true,
        patient: {
            age: 52,
            sex: "F",
            chiefComplaint: "«Se me mueven los dientes de arriba y se me han separado; me sangran desde hace años».",
            history: [
                "Sangrado crónico de larga evolución que la paciente «normalizó».",
                "Movilidad e inclinación del incisivo central superior derecho en el último año.",
                "Fumadora de 20 cigarrillos/día desde los 20 años.",
                "Hipertensa controlada con enalapril. Sin diabetes conocida (última glucemia 96 mg/dl).",
                "No acude al dentista desde hace más de 8 años.",
            ],
            background: ["Auxiliar administrativa", "Menopausia desde los 49 años"],
            habits: ["20 cigarrillos/día", "Cepillado irregular una vez al día", "Consumo de café elevado con tinción externa"],
        },
        clinicalFindings: [
            "Inflamación crónica generalizada con eritema y bolsa de 4–8 mm en múltiples sitios.",
            "Movilidad grado 2 en el 11 y grado 1 en el 21.",
            "Recesión vestibular de 1–3 mm con exposición radicular y sensibilidad al frío.",
            "BOP del 60 % de sitios, con supuración a la presión en la papila distal del 11.",
            "Radiográficamente: pérdida ósea horizontal del 35–50 % con defectos angulares.",
            "Sin dientes perdidos por periodontitis hasta la fecha.",
        ],
        photos: [{ caption: "Vestibular maxilar: inflamación crónica, recesiones y migración del 11 (ilustración esquemática)", kind: "periodontitis" }],
        radiograph: { caption: "Periapical del sector anterosuperior: pérdida ósea del 40 %", kind: "periapical", boneLossPct: 40 },
        perio: {
            toothId: "incisivo-central-sup",
            sites: {
                VMes: { pd: 6.0, rec: 1.0, bop: true, sup: true },
                VMed: { pd: 5.8, rec: 1.2, bop: true, sup: false },
                VDis: { pd: 7.0, rec: 1.0, bop: true, sup: true },
                PMes: { pd: 6.2, rec: 0.6, bop: true, sup: false },
                PMed: { pd: 5.5, rec: 0.5, bop: false, sup: false },
                PDis: { pd: 6.4, rec: 0.6, bop: true, sup: false },
            },
            mobility: 2,
        },
        conditionId: "perio-moderada",
        questions: [
            {
                id: "cg2-diag",
                kind: "diagnostico",
                prompt: "Con CAL ≥ 6 mm, pérdida ósea del 40 % y sin dientes perdidos por periodontitis, el diagnóstico es:",
                options: [
                    "Gingivitis asociada a biofilm",
                    "Periodontitis estadio III grado C",
                    "Periodontitis estadio II grado B",
                    "Periodontitis estadio IV grado B",
                ],
                correct: [1],
                multi: false,
                explanation: "CAL ≥ 5 mm con pérdida ósea > 33 % y ≤ 4 dientes perdidos → estadio III. Con 40 % de pérdida a los 52 años (40/52 ≈ 0.77, rango B) PERO fuma ≥ 20 cig/día, lo que eleva el grado a C.",
            },
            {
                id: "cg2-hallazgos",
                kind: "hallazgos",
                prompt: "Selecciona TODOS los hallazgos compatibles con destrucción periodontal activa.",
                options: [
                    "CAL de 6–7 mm desde el CEJ",
                    "Movilidad grado 2 en el 11",
                    "Supuración a la presión",
                    "Sondaje de 3 mm sin sangrado",
                    "Defectos angulares radiográficos",
                ],
                correct: [0, 1, 2, 4],
                multi: true,
                explanation: "CAL aumentada, movilidad, supuración y defectos angulares expresan destrucción; un sondaje de 3 mm sin sangrado sería compatible con salud.",
            },
            {
                id: "cg2-riesgo",
                kind: "riesgo",
                prompt: "¿Qué factores de riesgo deben abordarse SÍ o SÍ en el plan?",
                options: [
                    "Tabaquismo (20 cig/día)",
                    "Higiene oral deficiente",
                    "Menopausia como factor determinante",
                    "Ausencia de control glucémico reciente",
                ],
                correct: [0, 1, 3],
                multi: true,
                explanation: "El tabaquismo es el factor de riesgo principal (eleva el grado a C). La higiene deficiente sostiene el biofilm. Aunque la glucemia actual es normal, conviene descartar diabetes por la edad y el cuadro (solicitud de HbA1c). La menopausia es un contexto, no un factor de riesgo periodontal determinante por sí solo.",
            },
            {
                id: "cg2-pronostico",
                kind: "pronostico",
                prompt: "El pronóstico del 11 (movilidad 2, CAL 7 mm, supuración distal) tras terapia etiológica y control del tabaquismo es:",
                options: [
                    "Desesperado: indicar extracción inmediata",
                    "Reservado: probable mejoría de la inflamación y la movilidad; reevaluar antes de decidir",
                    "Excelente: recuperación completa de la inserción",
                    "Solo puede resolverse con implantes",
                ],
                correct: [1],
                multi: false,
                explanation: "El pronóstico del diente es reservado y dinámico: tras la terapia etiológica y el cese del tabaco suele reducirse la inflamación y la movilidad. La decisión sobre cirugía regenerativa, ferulización o extracción se toma en la reevaluación (4–6 semanas), nunca al inicio.",
            },
            {
                id: "cg2-plan",
                kind: "plan",
                prompt: "¿Cuál es la secuencia correcta del plan de tratamiento periodontal?",
                options: [
                    "Etiológica (higiene + RAR + deshabituación tabáquica) → reevaluación 4–6 semanas → correctiva de sitios residuales → soporte cada 3–4 meses",
                    "Cirugía inmediata de todos los sitios con bolsa y antibioterapia posterior",
                    "Extracción de los dientes con movilidad y rehabilitación protésica directa",
                    "Solo mantenimiento y reevaluación anual sin fase etiológica",
                ],
                correct: [0],
                multi: false,
                explanation: "La secuencia es siempre: fase etiológica → reevaluación → fase correctiva (si procede) → mantenimiento. El grado C obliga a intervalos de soporte cortos (3–4 meses) y el tabaquismo debe abordarse desde la primera consulta.",
            },
        ],
        teachingPoints: [
            "El tabaquismo ≥ 10 cig/día eleva el grado (C) y enmascara el sangrado: valora otros signos.",
            "La estadificación mira el daño (CAL, hueso, dientes perdidos); el grado, la velocidad y el riesgo.",
            "El pronóstico se decide tras la reevaluación: nunca extraer en la primera visita por movilidad reversible.",
        ],
    },
    {
        id: "caso-recesion",
        title: "Caso 3 · Raíz expuesta y sensibilidad en el 11",
        difficulty: "basico",
        builtin: true,
        patient: {
            age: 34,
            sex: "M",
            chiefComplaint: "«El cuello del diente se me ve más largo y me molesta el frío al cepillarme».",
            history: [
                "Sensibilidad al frío en el tercio cervical del 11 desde hace un año.",
                "Cepillado tres veces al día con cepillo duro y técnica horizontal intensa.",
                "Sin sangrado espontáneo ni al cepillado.",
                "Sin antecedentes médicos. No fumador.",
            ],
            background: ["Ingeniero", "Revisión dental anual"],
            habits: ["Cepillo duro", "Técnica horizontal vigorosa", "Sin higiene interproximal"],
        },
        clinicalFindings: [
            "Recesión vestibular del 11 de 3 mm, con margen apical a la línea mucogingival.",
            "Fenotipo fino: banda de encía queratinizada < 1 mm en el sector anterosuperior.",
            "Sondaje de 1–2 mm en todos los sitios, sin sangrado al sondaje (BOP 0 %).",
            "Sin movilidad ni pérdida ósea radiográfica.",
            "Frenillo labial superior con inserción baja y tracción visible sobre el margen.",
            "Abrasión cervical incipiente en la raíz expuesta.",
        ],
        photos: [{ caption: "Recesión vestibular del 11 con fenotipo fino (ilustración esquemática)", kind: "recession" }],
        perio: {
            toothId: "incisivo-central-sup",
            sites: {
                VMes: { pd: 1.5, rec: 2.2, bop: false, sup: false },
                VMed: { pd: 1.2, rec: 3.0, bop: false, sup: false },
                VDis: { pd: 1.4, rec: 2.4, bop: false, sup: false },
                PMes: { pd: 1.6, rec: 0, bop: false, sup: false },
                PMed: { pd: 1.3, rec: 0, bop: false, sup: false },
                PDis: { pd: 1.5, rec: 0, bop: false, sup: false },
            },
            mobility: 0,
        },
        conditionId: "sano",
        questions: [
            {
                id: "cg3-diag",
                kind: "diagnostico",
                prompt: "El diagnóstico periodontal del 11 es:",
                options: [
                    "Gingivitis inducida por biofilm",
                    "Periodontitis estadio I",
                    "Recesión gingival Miller clase II sobre periodonto sano",
                    "Recesión gingival Miller clase III",
                ],
                correct: [2],
                multi: false,
                explanation: "Hay recesión de 3 mm que sobrepasa la línea mucogingival SIN pérdida interproximal (PD 1–2 mm, sin sangrado ni hueso perdido): Miller clase II sobre un periodonto sano (el CAL del sitio vestibular medio es 1.2 + 3.0 = 4.2 mm pero de origen traumático-mucogingival, no inflamatorio destructivo).",
            },
            {
                id: "cg3-hallazgos",
                kind: "hallazgos",
                prompt: "Selecciona los factores causales más relevantes de la recesión:",
                options: [
                    "Trauma de cepillado (técnica horizontal + cepillo duro)",
                    "Fenotipo fino con encía queratinizada < 1 mm",
                    "Inserción baja del frenillo con tracción",
                    "Biofilm abundante y BOP elevado",
                ],
                correct: [0, 1, 2],
                multi: true,
                explanation: "El trauma mecánico sobre un fenotipo fino, agravado por la tracción del frenillo, explica la recesión. Aquí NO hay inflamación (BOP 0 %).",
            },
            {
                id: "cg3-riesgo",
                kind: "riesgo",
                prompt: "¿Qué riesgo principal conlleva la recesión no tratada?",
                options: [
                    "Pérdida inmediata del diente",
                    "Progresión de la recesión, sensibilidad, caries radicular y afectación estética",
                    "Bolsa periodontal profunda inevitable",
                    "Ninguno: es solo estético",
                ],
                correct: [1],
                multi: false,
                explanation: "Manteniendo el trauma, la recesión progresa y expone más raíz: sensibilidad, caries radicular y estética son las consecuencias; no hay bolsa por ausencia de inflamación destructiva.",
            },
            {
                id: "cg3-pronostico",
                kind: "pronostico",
                prompt: "Para la cobertura quirúrgica de la recesión (injerto de tejido conectivo), el pronóstico esperado es:",
                options: [
                    "Cobertura completa predecible (clase I–II, fenotipo tratable)",
                    "Imposible de cubrir quirúrgicamente",
                    "Solo se puede tunelizar",
                    "Requiere extracción y implante",
                ],
                correct: [0],
                multi: false,
                explanation: "Las recesiones de Miller I y II (sin pérdida interproximal) son las de mejor pronóstico de cobertura con injerto de tejido conectivo, con alta predictibilidad cuando se elimina el trauma y se corrige el fenotipo.",
            },
            {
                id: "cg3-plan",
                kind: "plan",
                prompt: "¿Cuál es la secuencia terapéutica correcta?",
                options: [
                    "1) Corregir la técnica de cepillado (suave, Bass modificado, cepillo blando) y controlar el frenillo; 2) tratar la sensibilidad; 3) valorar injerto de cobertura radicular",
                    "1) RAR subgingival agresivo del 11; 2) reevaluar",
                    "1) Cirugía de colgajo y osteotomía resectiva",
                    "1) Ferulizar el 11 y administrar antibióticos",
                ],
                correct: [0],
                multi: false,
                explanation: "Primero se elimina la causa (trauma) y se trata el síntoma; después se corrige el defecto mucogingival con injerto si hay indicación estética o de tejido queratinizado. No hay terapia antiinfecciosa que hacer: no hay periodontitis.",
            },
        ],
        teachingPoints: [
            "Recesión con PD normal y sin BOP: piensa en causa traumática/mucogingival, no inflamatoria.",
            "La clase de Miller predice la cobertura quirúrgica: I–II favorable, III–IV limitada.",
            "Siempre se trata primero la causa (técnica de cepillado, frenillo) antes que la cirugía.",
        ],
    },
];
